name: Manually Release MQTT Nuget

on:  
  workflow_dispatch:
    inputs:
      majorVersion:
        description: 'Major Verions for Semantic versioning'     
        required: true
        default: '0'
      minorVersion:
        description: 'Minor Verions'     
        required: true
        default: '0'
      patchVersion:
        description: 'Patch Verions'     
        required: true
        default: '1'

jobs:
  call-workflow-passing-data:
    uses: OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/.github/workflows/nugets/BaseNugetRelease.yml@main
    with:
      majorVersion: ${{ github.event.inputs.majorVersion }}
      minorVersion: ${{ github.event.inputs.minorVersion }}
      patchVersion: ${{ github.event.inputs.patchVersion }}
      projectName: 'Kafka'
      workingDirectory: 'src/Infrastructure/Kafka'
    secrets:
      PACKAGE_PUSH_KEY: ${{ secrets.PACKAGE_PUSH_KEY }}