version: '3.1'
services:
  opc-ua-server:
    image: "mcr.microsoft.com/iot/opc-ua-test-server:latest"
    container_name: opc-ua-server
    hostname: opc-ua-server
    restart: always
    command: --port 4840
    ports:
      - "4840:4840"

  broker-mqtt:
    image: "eclipse-mosquitto:1.6.15"
    container_name: broker-mqtt
    hostname: broker-mqtt
    ports:
      - "1883:1883"
    restart: always    

  omp-opc-ua-connector:
    image: "mqtttest1"
    depends_on:
      - broker-mqtt
      - opc-ua-server
    container_name: omp-opc-ua-connector
    restart: always
    environment:
      OpcUa__DefaultServerBrowseDepth: 3
      OpcUa__NodeBrowseDepth: 1
      OpcUa__EnableRegisteredNodes: 'false'
      OpcUa__SubscriptionBatchSize: 100
      OpcUa__ReadBatchSize: 100
      OpcUa__RegisterNodeBatchSize: 100
      Communication__SchemaUrl: 'https://iotpeweubsdm001st.blob.core.windows.net/schemas/'
      Communication__Shared__NativeSettings__brokerAddress: broker-mqtt
      Communication__Shared__NativeSettings__brokerPort: 1883
      Communication__Shared__NativeSettings__username: ''
      Communication__Shared__NativeSettings__password: ''
      Communication__Shared__NativeSettings__secure: 'false'
      Communication__Shared__NativeSettings__keepAlivePeriod: 60
      Communication__Shared__NativeSettings__autoReconnectTimeInSeconds: 10
      Communication__TelemetryEndpoint__NativeSettings__topics__0__topicName: 'telemetry'
      Communication__TelemetryEndpoint__NativeSettings__clientId: 'client-telemetry'
      Communication__CommandEndpoint__NativeSettings__topics__0__topicName: 'commands'
      Communication__CommandEndpoint__NativeSettings__clientId: 'client-commands'
      Communication__ResponseEndpoint__NativeSettings__topics__0__topicName: 'responses'
      Communication__ResponseEndpoint__NativeSettings__clientId: 'client-responses'
      Logging__LogLevel__Default: 'Information'
      DisableSubscriptionRestoreService: 'true'
      EnableMessageFilter: 'false'
      ConnectorId: '00000000-0000-0000-0000-000000000001'