////
Copyright (c) 2021 BMW Group

See the AUTHORS file(s) distributed with this work for additional information regarding authorship. 

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

[[site-notice]]
= Site Notice

This is an approved deliverable by the https://open-manufacturing.org[{omp} ({omp-abbr})].

THESE MATERIALS ARE PROVIDED "AS IS."
The parties expressly disclaim any warranties (express, implied, or otherwise), including implied warranties of merchantability, non-infringement, fitness for a particular purpose, or title, related to the materials.
The entire risk as to implementing or otherwise using the materials is assumed by the implementer and user.
IN NO EVENT WILL THE PARTIES BE LIABLE TO ANY OTHER PARTY FOR LOST PROFITS OR ANY FORM OF INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER FROM ANY CAUSES OF ACTION OF ANY KIND WITH RESPECT TO THIS DELIVERABLE OR ITS GOVERNING AGREEMENT, WHETHER BASED ON BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, AND WHETHER OR NOT THE OTHER MEMBER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

[[authors]]
== Authors

* Sebastian Buckel, BMW Group
* Hermo Terblanche, BMW Group

[[github]]
== GitHub

https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet


This work is provided by the copyright holders under the license MPL-2.0 as defined in https://www.mozilla.org/en-US/MPL/2.0/.
As the separate files in this project are developed independently from each other, copyright notices and alike, are part of those separate files.