version: '3.1'
services:
  hos-opc-ua-server:
    image: "mcr.microsoft.com/iot/opc-ua-test-server:latest"
    container_name: hos-opc-ua-server
    hostname: hos-opc-ua-server
    restart: always
    command: --port 4840
    ports:
      - "4840:4840"

  hos-broker-mqtt:
    image: "eclipse-mosquitto:1.6.15"
    container_name: hos-broker-mqtt
    hostname: hos-broker-mqtt
    ports:
      - "1883:1883"
    restart: always    

  omp-opc-ua-connector:
    image: "mqttest1"
    depends_on:
      - hos-broker-mqtt
      - hos-opc-ua-server
    container_name: hos-omp-opc-ua-connector
    restart: always
    environment:
      OpcUa__DefaultServerBrowseDepth: 3
      OpcUa__NodeBrowseDepth: 1
      OpcUa__EnableRegisteredNodes: 'false'
      OpcUa__SubscriptionBatchSize: 100
      OpcUa__ReadBatchSize: 100
      OpcUa__RegisterNodeBatchSize: 100
      Communication__SchemaUrl: 'https://iotpeweubsdm001st.blob.core.windows.net/schemas/'
      Communication__Shared__NativeSettings__brokerAddress: hos-broker-mqtt
      Communication__Shared__NativeSettings__brokerPort: 1883
      Communication__Shared__NativeSettings__username: ''
      Communication__Shared__NativeSettings__password: ''
      Communication__Shared__NativeSettings__secure: 'false'
      Communication__Shared__NativeSettings__keepAlivePeriod: 60
      Communication__Shared__NativeSettings__autoReconnectTimeInSeconds: 10
      Communication__TelemetryEndpoint__NativeSettings__topics__0__topicName: 'telemetry'
      Communication__TelemetryEndpoint__NativeSettings__clientId: 'client-telemetry'
      Communication__CommandEndpoint__NativeSettings__topics__0__topicName: 'commands'
      Communication__CommandEndpoint__NativeSettings__clientId: 'client-commands'
      Communication__ResponseEndpoint__NativeSettings__topics__0__topicName: 'responses'
      Communication__ResponseEndpoint__NativeSettings__clientId: 'client-responses'
      Logging__LogLevel__Default: 'Information'
      DisableSubscriptionRestoreService: 'true'
      EnableMessageFilter: 'false'
      ConnectorId: '00000000-0000-0000-0000-000000000001'    

  omp-hos-ui:
    image: "omphostui"
    depends_on:
      - omp-opc-ua-connector
    container_name: hos-ui
    hostname: hos-ui
    ports:
      - "8087:80"
    restart: always
    environment:
      mqtt__clientId: omp-hos-ui-client
      mqtt__brokkerAddress: hos-broker-mqtt
      mqtt__brokkerPort: 1883
      mqtt__requestTopicName: commands
      mqtt__responseTopicName: responses
      mqtt__telemetryTopicName: telemetry
      mqtt__hubAddress: http://hos-ui:8087/handsOnHub