name: Manually Release Domain.Schema Nuget

on:  
  workflow_dispatch:
    inputs:
      majorVersion:
        description: 'Major Verions for Semantic versioning'     
        required: true
        default: '0'
      minorVersion:
        description: 'Minor Verions'     
        required: true
        default: '0'
      patchVersion:
        description: 'Patch Verions'     
        required: true
        default: '1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet build Domain.Schema.csproj -c Release -v n /p:Version=${{ github.event.inputs.majorVersion }}.${{ github.event.inputs.minorVersion }}.${{ github.event.inputs.patchVersion }}-pre-release /p:PackageReleaseNotes="See https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Domain.Schema   
    - name: Publish Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/OpenManufacturingPlatform/index.json" --no-symbols true
