name: Manually Release Domain Nuget

on:  
  workflow_dispatch:
    inputs:
      majorVersion:
        description: 'Major Versions for Semantic versioning'
        required: true
        default: '0'
      minorVersion:
        description: 'Minor Versions'
        required: true
        default: '0'
      patchVersion:
        description: 'Patch Versions'
        required: true
        default: '1'

jobs:
  call-workflow-passing-data:
    uses: OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/.github/workflows/BaseNugetRelease.yml@main
    with:
      majorVersion: ${{ github.event.inputs.majorVersion }}
      minorVersion: ${{ github.event.inputs.minorVersion }}
      patchVersion: ${{ github.event.inputs.patchVersion }}
      projectName: 'Domain.Schema'
      workingDirectory: 'src/Domain'
    secrets:
      PACKAGE_PUSH_KEY: ${{ secrets.PACKAGE_PUSH_KEY }}