name: Release Nuget Packages

on:  
  release:
    types: [published]
  push:
    branches:
      - components/nuget-builds

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build Domain Schema
      run: dotnet build Domain.Schema.csproj -c Release -v n /p:Version=0.0.0.2-alpha01 /p:PackageReleaseNotes="See https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Domain.Schema   
    - name: Publish Domain.Schema Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/OpenManufacturingPlatform/index.json" --no-symbols true

    - name: Build Domain
      run: dotnet build Domain.csproj -c Release -v n /p:Version=0.0.0.2-alpha01 /p:PackageReleaseNotes="See https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Domain
    - name: Publish Domain Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/OpenManufacturingPlatform/index.json" --no-symbols true
      
    - name: Build Application
      run: dotnet build Application.csproj -c Release -v n /p:Version=0.0.0.2-alpha01 /p:PackageReleaseNotes="See https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Application
    - name: Publish Domain Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/OpenManufacturingPlatform/index.json" --no-symbols true
      
    - name: Build OpcUa
      run: dotnet build OpcUa.csproj -c Release -v n /p:Version=0.0.0.2-alpha01 /p:PackageReleaseNotes="See https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Infrastructure/OpcUa
    - name: Publish Domain Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/OpenManufacturingPlatform/index.json" --no-symbols true
      
    - name: Build MQTT
      run: dotnet build MQTT.csproj -c Release -v n /p:Version=0.0.0.2-alpha01 /p:PackageReleaseNotes="See https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Infrastructure/MQTT
    - name: Publish Domain Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/OpenManufacturingPlatform/index.json" --no-symbols true
      
    - name: Build Kafka
      run: dotnet build Kafka.csproj -c Release -v n /p:Version=0.0.0.2-alpha01 /p:PackageReleaseNotes="See https://github.com/OpenManufacturingPlatform/iotcon-opc-ua-connector-dotnet/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Infrastructure/Kafka
    - name: Publish Domain Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/OpenManufacturingPlatform/index.json" --no-symbols true
