name: Build & Test Solution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore OMP-Opc-Ua-Connector.sln
    - name: Build
      run: dotnet build OMP-Opc-Ua-Connector.sln --no-restore
    - name: Test
      run: dotnet test OMP-Opc-Ua-Connector.sln --no-build --verbosity normal