name: Release Domain.Schema Nuget

on:  
  release:
    types: [published]
  push:
    branches:
      - components/nuget-builds

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build Domain.Schema.csproj -c Release -v n /p:Version=0.0.0.1-alpha01 /p:PackageReleaseNotes="See https://github.com/KitsKlip/ExpressionBuilder/tags/${{ github.event.release.tag_name }}"
      working-directory: src/Domain.Schema   
    - name: Publish Package to GitHub
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PACKAGE_PUSH_KEY }} --source "https://nuget.pkg.github.com/KitsKlip/index.json" --no-symbols true
